### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlua#107]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by ryanplusplus** [comment]
No problem here

**Comment by kytrinyx** [comment]
The test says isosceles? Or there is no such test?

**Comment by ryanplusplus** [comment]
Oh! I thought I was supposed to make sure that such a test existed and if not, created. The test exists, but is incorrect. It indicates that it is invalid, not isosceles. Thanks.

**Comment by kytrinyx** [comment]
Sorry, my bad. There's a discussion in another track that says wolfram alpha disagrees with wikipedia on the 2, 2, 4 case. I think hold off until we actually do some more research.

**Comment by ryanplusplus** [comment]
@kytrinyx have we come to a consensus on this? Is there somewhere to follow the discussion?

**Comment by kytrinyx** [comment]
The discussion is here: https://github.com/exercism/xerlang/issues/85

I think we're at the point where we should just make a decision, but I've been traveling for the past few days and haven't had time to re-read through the issues and make a suggestion as to the best solution.
