### ISSUE TITLE
exception in regexp

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlua#117]
I'm getting the following error:

```
757: unexpected token at 'Puma caught this error: target of
repeat operator is not specified: /*spec[.]lua$/ (RegexpError)
```

The regexp should probably be `".*spec[.]lua$"` (starting with a `"."`).

**Comment by ryanplusplus** [comment]
Thanks! Let me try that.

**Comment by kytrinyx** [comment]
I'm submitting a patch -- tested locally, it looks like it works.
