### ISSUE TITLE
Error accessing test suite

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xlua#119]
@kytrinyx we're still having issues getting the test suite for Lua exercises. How can I help to debug this?

For example:
http://exercism.io/exercises/lua/allergies

**Comment by kytrinyx** [comment]
I wonder if I forgot to update the api after fixing the regex yesterday. Checking now.

**Comment by kytrinyx** [comment]
Yepp. Doing that now. I'll also check that page after deploying.

**Comment by ryanplusplus** [comment]
Excellent, thanks!

**Comment by ryanplusplus** [comment]
Works now, thanks again!

**Comment by kytrinyx** [comment]
Yay! Cool. Thanks for following up on that one.
