### ISSUE TITLE
Verify "Largest Series Product" exercise implementation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlua#130]
There was some confusion in this exercise due to the ambiguous use of the term _consecutive_ in the README. This could be taken to mean _contiguous_, as in consecutive by position, or as in _consecutive numerically_. The the README has been fixed (https://github.com/exercism/x-common/pull/200).

**Please verify that the exercise is implemented in this track correctly** (that it finds series of contiguous numbers, not series of numbers that follow each other consecutively).

If it helps, the canonical inputs/outputs for the exercise can be found here:
https://github.com/exercism/x-common/blob/master/largest-series-product.json

If everything is fine, go ahead and just close this issue. If there's something to be done, then please describe the steps needed in order to close the issue.

**Comment by aarti** [comment]
It is  implement correctly on this track. The series_product is a function that is called with first and last indices. The last index being the first + span
`series_product(digits, i, i + config.span - 1)`

```
local function series_product(a, first, last)
  local product = 1
  for i = first, last do
    product = product * a[i]
  end
  return product
end
```
