### ISSUE TITLE
Duplicated installation instructions

### ISSUE THREAD

**Issue by robphoenix** [exercism/xlua#188]
I was going to update the README to cover setting up a dev environment for Linux & Windows, but then realised that that would mean the installation instructions would be repeated in 3 separate places; in [SETUP.md](https://github.com/exercism/xlua/blob/master/SETUP.md), [INSTALLATION.md](https://github.com/exercism/xlua/blob/master/docs/INSTALLATION.md) and then in the README, meaning that if there were ever any changes then they would need to be updated in all of these places.

Would it be better to only have the installation instructions in INSTALLATION.md and then reference them (at http://exercism.io/languages/lua/installing) from the README and SETUP files? This would also remove the repetition of having extensive installation instructions in the README of each exercise, which shouldn't really be necessary past the first exercise.

**Comment by ryanplusplus** [comment]
I like the idea of only including instructions in one place. It looks like `SETUP.md` is probably a relic of the past (not included in most tracks as far as I can tell) and `README.md` doesn't get referenced by Exercism internals. So I think that all we need to do is remove `SETUP.md` and then link to `INSTALLATION.md` from `README.md`.

**Comment by robphoenix** [comment]
closed by #190

**Comment by petertseng** [comment]
> `SETUP.md` is probably a relic of the past

That depends - https://github.com/exercism/exercism.io/issues/3240 tells us the goal is to move it to exercises/TRACK_HINTS.md

What will happen if either a `SETUP.md` or `TRACK_HINTS.md` is present? Its contents get included in the README delivered to the student for every problem.

So if y'all have any instructions that you think are worth it to include in the README, that would be the place for them. Most tracks that I see have a reminder of how to run the tests, so it could be worth it to place a reminder of `busted .` there.

Y'all are right to say that there is the danger of some duplicate instructions between TRACK_HINTS.md and docs/TESTS.md - there was an issue https://github.com/exercism/x-common/issues/229 for that, but perhaps nobody cared enough about duplication at the time to comment.
