### ISSUE TITLE
By default busted looks for *_spec.lua

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xlua#70]
Right now all tests are named `*_test.lua` which requires users to invoke `busted *_test.lua`. If we changed all of the test files to `*_spec.lua`, then we'd only need to instruct users to invoke `busted .`.

I think we should rename the test files. I'm happy to change all of these if everyone's in agreement.

Note that this would make resolving #19 trivial.

**Comment by kytrinyx** [comment]
That seems like a good idea to me. What do you think, @aarti?
